config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: {registrations: 'users/registrations'}
devise_scope :user do
  get "edit_place_and_radius", to: "users/registrations#edit_place_and_radius", as: :edit_place_and_radius
  patch "update_place_and_radius", to: "users/registrations#update_place_and_radius", as: :update_place_and_radius
end

  resources :gardens, except: [:destroy, :new] do
    resources :bookings, only: [:new, :create, :show]
  end
  delete 'delete_garden', to: "gardens#destroy", as: :delete_garden
  get 'new_garden', to: "gardens#new", as: :new_garden
  get "my_gardens", to: "gardens#my_gardens", as: :my_gardens

  delete 'delete_booking', to: 'bookings#destroy', as: :delete_booking
  get "bookings", to: "bookings#my_bookings", as: :my_bookings
  get "show_from_booking_action", to: "bookings#show_from_booking_action", as: :show_from_booking_action # >>> put in nested resources, such as :show
  get "my_account", to: "pages#my_account", as: :my_account

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :garden
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update ]
  before_action :set_booking_format, only: [:destroy ]


  def index
  end

  def my_bookings
    @bookings = BookingPolicy::Scope.new(current_user, Booking).scope.where(booker_id: current_user.id)
  end

  def show
    if params[:id] == current_user.id.to_s
      @booking = Booking.find(params[:garden_id])
    elsif
      @booking = Booking.find(params[:id])
    else
      @booking = Booking.find(params[:garden_id])
    end
    authorize @booking
  end

  def new
    @garden = Garden.find(params[:garden_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @garden = Garden.find params[:garden_id]
    @booking = @garden.bookings.build(date: DateTime.now.to_date)
    @booking.booker_id = current_user.id.to_i
    @garden.availabilities = false
    @garden.save
    authorize @booking
    if @booking.save
      redirect_to garden_booking_path( current_user, @booking)
    end
  end

  def update
  end

  def edit
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to my_bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_booking_format
    @booking = Booking.find(params[:format])
  end
  def booking_params
    params.require(:booking).permit(:garden_id, :booker_id, :date)
  end
end

app/views/bookings/my_bookings.html.erb
<h1>My Bookings</h1>
<% @bookings.each do |booking| %>
  <li>
  <%= link_to booking.garden.title, garden_booking_path(booking,current_user) %> //
  <%  booker = User.where(id: booking.booker_id).first.email %>
  <p> Booker : <%= booker %></p>
  <% owner_id = Garden.where(id: booking.garden_id).last.user_id %>
  <p> Owner : <%= owner = User.where(id: owner_id).last.email %></p>
  </li>
<% end %>

</ul>
  <li><%= link_to "My Account", my_account_path %></li>
  <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
  <li><%= link_to "home", root_path %></li>
  <% if current_user.admin == false %>
  <% end %>

app/views/bookings/new.html.erb
THIS PAGE IS NOT USED BUT KEPT IN ORDER TO HAVE A MODEL OF AUTOCOMPLETE SIMPLE_FORM FOR LATER IF NEEDED

<h1>My booking</h1>
  <%= simple_form_for [@garden, @booking] do |f| %>
  <%= f.input :booker_id, input_html: {value: current_user.id}, disabled: true %>
  <%= f.input :garden, input_html: {value: @garden.title}, disabled: true %>
  <%= f.input :date, input_html: {value: DateTime.now.to_date} %>
  <%= f.submit %>
  <% end %>

app/views/bookings/show.html.erb
<h1>your booking</h1>
<%= @booking.garden.title %>

<li><%= link_to "My bookings", my_bookings_path %></li>
<li><%= link_to "HOME", root_path %></li>
<li><%= link_to "Cancel my booking", delete_booking_path(@booking, current_user), method: :delete %></li>
<li><%= "Send a message to the owner" %></li>

app/views/bookings/show_from_booking_action.html.erb
<h1>your booking</h1>
<%= @booking.garden.title %>

<li><%= link_to "My bookings", my_bookings_path %></li>
<li><%= link_to "HOME", root_path %></li>
<li><%= link_to "Cancel my booking", delete_booking_path(@booking, current_user), method: :delete %></li>
<li><%= "Send a message to the owner" %></li>