config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: {registrations: 'users/registrations'}
devise_scope :user do
  get "edit_place_and_radius", to: "users/registrations#edit_place_and_radius", as: :edit_place_and_radius
  patch "update_place_and_radius", to: "users/registrations#update_place_and_radius", as: :update_place_and_radius
end

  resources :gardens, except: [:destroy, :new] do
    resources :bookings, only: [:new, :create, :show]
  end
  delete 'delete_garden', to: "gardens#destroy", as: :delete_garden
  get 'new_garden', to: "gardens#new", as: :new_garden
  get "my_gardens", to: "gardens#my_gardens", as: :my_gardens

  delete 'delete_booking', to: 'bookings#destroy', as: :delete_booking
  get "bookings", to: "bookings#my_bookings", as: :my_bookings
  get "show_from_booking_action", to: "bookings#show_from_booking_action", as: :show_from_booking_action # >>> put in nested resources, such as :show
  get "my_account", to: "pages#my_account", as: :my_account

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="home-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(https://frarborists.com/dev/wp-content/uploads/shutterstock_126246674.jpg">
  <div class="row justify-content-center w-100">
    <h1>Welcome at <br/>Gardens in the Walls</h1>
  </div>
  <div class="row banner-menu w-100">
        <%= link_to "My account", my_account_path %>
        <%= link_to "Go picking", edit_place_and_radius_path(@user) %>
  </div>
</div>

app/views/pages/my_account.html.erb
<%= render "shared/navbar" %>
<div class="container index-container mt-5 d-flex flex-column">
  <div class="row index-title-row ">
    <h1>My Account</h1>
  </div>
  <div class="row text-white d-flex justify-content-around">
    <button type="button" class="btn border shadow-lg mt-5px"><%= link_to "My Bookings", my_bookings_path %></button>
    <button type="button" class="btn border shadow-lg mt-5px"><%= link_to "My gardens published", my_gardens_path %></button>
    <button type="button" class="btn border shadow-lg mt-5px"><%= link_to "Change my identifiers", edit_user_registration_path %></button>
  </div>
</div>