config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: {registrations: 'users/registrations'}
devise_scope :user do
  get "edit_place_and_radius", to: "users/registrations#edit_place_and_radius", as: :edit_place_and_radius
  patch "update_place_and_radius", to: "users/registrations#update_place_and_radius", as: :update_place_and_radius
end

  resources :gardens, except: [:destroy, :new] do
    resources :bookings, only: [:new, :create, :show]
  end
  delete 'delete_garden', to: "gardens#destroy", as: :delete_garden
  get 'new_garden', to: "gardens#new", as: :new_garden
  get "my_gardens", to: "gardens#my_gardens", as: :my_gardens

  delete 'delete_booking', to: 'bookings#destroy', as: :delete_booking
  get "bookings", to: "bookings#my_bookings", as: :my_bookings
  get "show_from_booking_action", to: "bookings#show_from_booking_action", as: :show_from_booking_action # >>> put in nested resources, such as :show
  get "my_account", to: "pages#my_account", as: :my_account

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/garden.rb
class Garden < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :address, presence: true, uniqueness: true
  validates :title, presence: true

  belongs_to :user
  has_many :bookings, dependent: :destroy
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update ]
  def new
    @garden = Garden.new
    authorize @garden
  end

  def create
    @garden = Garden.new(garden_params)
    authorize @garden
#    authorize @garden, policy_scope_class: GardenPolicy::Myscope   ???

    @garden.user = current_user
# OU :     @garden = current_user.gardens.build(garden_params)

    respond_to do |format|
      if @garden.save
        format.html { redirect_to @garden, notice: 'Garden was successfully created.' }
        format.json { render :show, status: :created, location: @garden }
      else
        format.html { render :new }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    # REMPLACER PAR
    lat = current_user.latitude
    lon = current_user.longitude
    radius = current_user.search_radius
    @gardens = policy_scope(Garden).near([lat, lon], radius)

  #    @gardens = policy_scope(Garden)
  end

  def my_gardens
    @gardens = GardenPolicy::Scope.new(current_user, Garden).scope.where(user_id: current_user)
  end

  def show
    authorize @garden
  end

  def destroy
    @garden = Garden.find(params[:format])
    authorize @garden
    @garden.destroy
#      format.html { redirect_to my_gardens_path, notice: 'garden was successfully destroyed.' }
#      format.json { head :no_content }
#    else
#      "sorry it was not deleted"
#    end
    redirect_to my_gardens_path
  end

  def edit
    authorize @garden
  end

 def update
  authorize @garden

  respond_to do |format|
    if @garden.update(garden_params)
      format.html { redirect_to @garden, notice: 'Garden was successfully updated.' }
      format.json { render :show, status: :ok, location: @garden }
    else
      format.html { render :edit }
      format.json { render json: @garden.errors, status: :unprocessable_entity }
    end
  end
end

  private

  def garden_params
    params.require(:garden).permit(:title, :details, :surface, :address, :availabilities, :user)
  end

  def set_garden
    @garden = Garden.find(params[:id])
  end
end

app/views/gardens/_form.html.erb
  <%= simple_form_for(@garden) do |f| %>
  <%= f.input :title %>
  <%= f.input :address %>
  <%= f.input :details %>
  <%= f.input :surface %>
  <%= f.input :availabilities, label: "Available?" %>
  <%= f.submit %>

<% end %>

app/views/gardens/edit.html.erb
<h1>Edit</h1>
<%= render "form" %>

app/views/gardens/index.html.erb
<%= render "shared/navbar" %>

<!-- NAVBAR END -->


<div class="container index-container mt-5 d-flex flex-column">
  <div class="row index-title-row d-flex flex-column ">
    <h1>Gardens around you</h1>
    <% if current_user.admin == true %>
      <b><%= "ADMIN STATUS" %></b>
    <% else %>
      <b><%= "USER STATUS" %></b>
    <% end %>
  </div>

  <div class="row index-cards-container ">
    <div class="cards col-md-8
    flex-row">
      <% @gardens.each do |garden| %>

        <div class="card border border-white rounded shadow-lg p-3 mb-5 mr-0 bg-white">
            <img class="card-img-top" src="https://www.telegraph.co.uk/content/dam/gardening/2016/10/07/trees_trans_NvBQzQNjv4BqgsaO8O78rhmZrDxTlQBjdGLvJF5WfpqnBZShRL_tOZw.jpg?imwidth=1240" alt="Card image cap">
          <div class="card-body pb-0 text-dark">
            <h5><%= garden.title %></h5>
            <p> Status :
              <% if garden.availabilities == false %>
                <%= 'unavailable :(' %>
              <% else %>
               <%= "available :)" %>
              <% end %>
            </p>
            <button type="button" class="btn btn-primary shadow-lg mt-5px"><%= link_to "see details", garden_path(garden) %></button>
          </div>
        </div>
      <% end %>
          </div>
        <img id="map" src='https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/2.346,48.8595,11.72,0,0/600x1000?access_token=pk.eyJ1IjoianVsaWVicm9zc2UiLCJhIjoiY2p2bWVzOTBoMThkMDQ5czJ1cnl6d3g4NiJ9.iObbDJ4n4tOjspS41cvsSg' style="width: 30%">
  </div>
</div>

app/views/gardens/my_gardens.html.erb
<%= render "shared/navbar" %>

<div class="container index-container mt-5 d-flex flex-column">
  <div class="row index-title-row ">
    <h1>My gardens</h1>
  </div>

  <div class="row">
    <% @gardens.each do |garden| %>
      <div class="col-xs-12 col-sm-6 col-md-4">

        <div class="card border border-white rounded shadow-lg p-3 mb-5 bg-white">
            <img class="card-img-top" src="https://www.telegraph.co.uk/content/dam/gardening/2016/10/07/trees_trans_NvBQzQNjv4BqgsaO8O78rhmZrDxTlQBjdGLvJF5WfpqnBZShRL_tOZw.jpg?imwidth=1240" alt="Card image cap">
          <div class="card-body pb-0 text-dark">
            <h5><%= link_to "#{garden.title}", garden_path(garden) %></h5>
            <p> Status :
              <% if garden.availabilities == false %>
                <%= 'unavailable' %>
              <% else %>
               <%= "available" %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    <%end%>
  </div>



  <div class="row">
    <button type="button" class="btn btn-success shadow-lg btn-lg"><%= link_to "Add a garden", new_garden_path %></button>
  </div>
</div>

app/views/gardens/new.html.erb
<%= render "shared/navbar" %>

<h1>Add a new Garden</h1>
<%= render "form" %>

app/views/gardens/show.html.erb
<%= render "shared/navbar" %>
<div class="row banner-show background d-flex justify-content-center border boder-black m-0">
   <img src="https://www.harvesttotable.com/wp-content/uploads/2009/07/Apple-tree-with-fruit-300x300.jpg" alt="">
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col-sm-4 d-flex justify-content-between d-flex flex-column">
      <div class="d-flex justify-content-between">
        <div class="d-flex flex-column">
          <h1 class="text-capitalize"><%= @garden.title  %></h1>
          <p class="mb-5">Subtitle</p>
        </div>
        <div>
          <img class="avatar-show" src="https://avatars0.githubusercontent.com/u/414418?s=400&v=4"  alt="">
          <% if policy(@garden).destroy? %>
            <div>
              <a class="text-decoration-none text-dark"><%= link_to "Delete", delete_garden_path(@garden), method: :delete %> //</a>
              <a><%= link_to "edit", edit_garden_path %></a>
            </div>
          <% end %>
        </div>
      </div>
      <h5 >Details :</h5><p> <%= @garden.details %></p>
      <h5>Location :</h5> <p><%= @garden.address %></p>
      <h5>Surface : </h5><p><%= @garden.surface %> m2</p>
      <p> Here will appear the availabilities to select</p>
    </div>

      <div  class="col-sm-4 offset-sm-4 d-flex flex-column">
        <div class="card boder p-5 border rounded">
          <% if @garden.availabilities == true %>
            <p>Fruits are ready to be picked</p>
            <p class="btn btn-success"><%= link_to "Book the Garden", garden_bookings_path(@garden), method: :post %></p>
          <% else %>
            <p>This garden is currently unavailable</p>
          <% end %>
        </div>
        <a><%= link_to "Gardens", gardens_path %></a>
        <a><%= link_to "My gardens", my_gardens_path %></a>
      </div>
  </div>
</div>